### ISSUE TITLE
[OTHER] Show "Skill Level" for alternatives

### ISSUE THREAD

**Issue by tycrek** [tycrek/degoogle#137]
As mentioned in issue #131, there is interest in adding a "skill level" to each alternative in the list. This will take some time to determine the skill level for everything in the list.

For adding this into the guide, it is easiest to use the recently implemented [degoogle.yml](../blob/master/degoogle.yml) and GitHub Action to update the READEME. A sample for what could be shown in the `.yml`:

```yaml
- name: Syncthing
  url: https://syncthing.net/
  eyes: 9
  skill: 1
  text: |
    An interesting take on cloud storage: decentralized. Peer-to-peer between only your devices. Software is open-source and available on GitHub.
```

Skills levels could be internally zero-indexed as the following:

- 0: Beginner (not much configuration or technical knowledge required. Ex: Firefox)
- 1: Intermediate (a bit more tricky for the average user. Some knowledge of open-source, self-hosting, or other technical knowledge might be required. Ex: Syncthing, Piwigo)
- 2: Advanced (knowledge of Linux & programming will probably be required, or advanced knowledge of networking and security. Ex: TAILS, Moodle self-hosted)

These are by no means set in stone and have the potential to be improved. Use this issue for discussion and for keeping track of proposed Skill Levels. If proposing a skill level, please leave a brief summary of why it deserves that level.
